config/routes.rb
Rails.application.routes.draw do


  #does this need to be PLURAL? blogs#index
  #hey Paris! It's Elie....why would you name a controller blog??
  #you have two controllers....authors and posts....
  #wtf is blog????? Let's fix that below....Pat concurs...
  root 'authors#index'

  resources :authors do
    resources :posts, shallow: true
  end


#            root GET    /                                       authors#index
#    author_posts GET    /authors/:author_id/posts(.:format)     posts#index
#                 POST   /authors/:author_id/posts(.:format)     posts#create
# new_author_post GET    /authors/:author_id/posts/new(.:format) posts#new
#       edit_post GET    /posts/:id/edit(.:format)               posts#edit
#            post GET    /posts/:id(.:format)                    posts#show
#                 PATCH  /posts/:id(.:format)                    posts#update
#                 PUT    /posts/:id(.:format)                    posts#update
#                 DELETE /posts/:id(.:format)                    posts#destroy
#         authors GET    /authors(.:format)                      authors#index
#                 POST   /authors(.:format)                      authors#create
#      new_author GET    /authors/new(.:format)                  authors#new
#     edit_author GET    /authors/:id/edit(.:format)             authors#edit
#          author GET    /authors/:id(.:format)                  authors#show
#                 PATCH  /authors/:id(.:format)                  authors#update
#                 PUT    /authors/:id(.:format)                  authors#update
#                 DELETE /authors/:id(.:format)                  authors#destroy

end

app/models/author.rb
class Author < ActiveRecord::Base
	validates :first_name, :last_name, presence: true
	validates :first_name, length: {in: 4..20}
	validates :last_name, length: {in: 4..20}
	validates :age, numericality: true 	

	has_many :posts, dependent: :destroy
end

app/models/post.rb
class Post < ActiveRecord::Base
	 belongs_to :author
	 	validates :title, :body, :category, presence: true
	 	validates :title, length: {in: 3...20}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
  	@authors=Author.all
  end


  def new
  	@author=Author.new   
  end


  def show
  	@author=Author.find params[:id]
  end

  def edit
    @author=Author.find params[:id]
  end


  def create
    @author=Author.new author_params
    if @author.save
      redirect_to authors_path, notice: 'Author was successfully created'
    else
      render :new
    end
  end

  def update
    @author=Author.find params[:id]
    if @author.update_attributes author_params
      redirect_to author_path(@author), notice: 'Author was successfully updated'
    else 
      render :edit
    end
  end


  def destroy
    author=Author.find params[:id]
    author.destroy
    redirect_to authors_path, notice: 'Author was successfully destroyed'
  end

private
def author_params
	params.require(:author).permit(:first_name, :last_name, :age)
end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@author = Author.find params[:author_id]
  	@posts = @author.posts
  end

  def show
    	@post=Post.find params[:id]
    	@author=@post.author
  end

  def new
  	@author=Author.find params[:author_id]
  	@post=Post.new
  end

  def edit
  	@post=Post.find params[:id]
  	@author=@post.author
  end

  def create
  	@author=Author.find params[:author_id]
  	@post=Post.new post_params
  	@post.author = @author
  	if @post.save
  		redirect_to author_posts_path(@author)
  	else
  		render :new
  	end
  end

  def update
  	@post=Post.find params[:id]
  	@post.update_attributes post_params
  	@author = @post.author
  	if @post.save
  		redirect_to post_path(@post)
  	else
  		render :edit
  	end
  end

  def destroy
  	post=Post.find params[:id]
  	post.destroy
  	
  	redirect_to author_posts_path(post.author)
  end

  private
  def post_params
  	params.require(:post).permit(:title, :body, :category, :author_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/authors/edit.html.erb
<h1>Edit this author</h1>


<% if @author.errors.any?%>
	<% @author.errors.full_messages.each do |error|%>
		<p class="text-danger">
			<%= error %>
		</p>
	<% end %>
<% end %>


<%= form_for @author do |f| %>
<p class="form-center">
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</p>
<p class="form-center">
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</p>
<p class="form-center">
	<%= f.label :age %>
	<%= f.number_field :age %>
</p>
<p class="form-center">
	<%= f.submit %>
</p>
<% end %>

<p>
<%= link_to "Delete", author_path(@author), method: "delete", data: { confirm: "Are you sure you want to remove this author?"} %>
</p>
<p>
<%= link_to "Back to #{@author.first_name}", author_path %>
</p>

app/views/authors/index.html.erb
<h1>Check out our awesome authors!</h1>

<% @authors.each do |author| %>


<p>
<li>
<%= link_to author.first_name,  author_path(author) %>
</li>
</p>
<% end %>

<p>
<%= link_to "Add a New Author", new_author_path %>
</p>

app/views/authors/new.html.erb
<h1>Add an Author Below:</h1>

<div class="form">
<%= form_for @author do |f| %>
<p class="form-center">
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</p>
<p class="form-center">
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</p>
<p class="form-center">
	<%= f.label :age %>
	<%= f.number_field :age %>
</p>
<p class="form-center">
	<%= f.submit %>
</p>

<% end %>
</div>
<%= link_to "Authors Page", authors_path %>

app/views/authors/show.html.erb
<h1>Here's some info about <%= @author.first_name %></h1>

<p><%= @author.first_name %>  <%= @author.last_name %></p>
<p>Age: <%= @author.age %></p>


<%= link_to "Check out some of #{@author.first_name}'s posts", author_posts_path(@author) %> 

<p>
<%= link_to "Edit this author",  edit_author_path(@author)%>
</p>

<%= link_to "Back to All Authors", authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit this Post</h1>

<% if @post.errors.any?%>
	<% @post.errors.full_messages.each do |error|%>
		<p class="text-danger">
			<%= error %>
		</p>
	<% end %>
<% end %>


<%= form_for @post do |p| %>

<p>
	<%= p.label :title %>
	<%= p.text_field :title %>
</p>
<p>
	<%= p.label :category %>
	<%= p.text_field :category %>
</p>
<p>
	<%= p.label :body %>
	<%= p.text_area :body %>
</p>
<p>
	<%= p.submit %>
</p>
<% end %>

<%= link_to "Delete Article", post_path(@post), method: "delete", data: { confirm: "Are you sure you want to delete this article?"} %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Here are the author's articles:</h1>


	
<%= @posts.each do |post| %>
<ul>	
<li class="box">
	<%= link_to post.title, post_path(post)  %>
</li>
</ul>
<% end %>
<p>
<%= link_to "Add an article", new_author_post_path %>
</p>
<p>
<%= link_to "Back to Author's info", author_path(@author) %>
</p>

app/views/posts/new.html.erb
<h1>Make a new post!</h1>

<%= form_for ([:author, @post]) do |p| %>
	<p class="form-center">
		<%= p.label :title %>
		<%= p.text_field :title %>
	</p>
	<p class="form-center">
		<%= p.label :category	%>
		<%= p.text_field :category %>
	</p>
	<p class="form-center">
		<%= p.label :body %>
		<%= p.text_area :body %>
	</p>
	<p>
		
	</p class="form-center">
<%= p.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.title %></p>
<p><%= @post.category %></p>
<p><%= @post.body %></p>

<p>
<%= link_to "Edit this post",  edit_post_path%>
</p>

<p>
	<%= link_to "Back to Articles", author_posts_path(@author) %>
</p>